### PR TITLE
Added Travis CI.

### PR DESCRIPTION
**Pull request by Bplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by fabxc** [comment]
With `dep` one apparently doesn't check in `vendor/` so we should add ` go get github.com/golang/dep/cmd/dep` to the install-tools target can have Travis call `dep ensure` as part of `install`.

I hope this doesn't make CI runs crazy long.

**Comment by Bplotka** [comment]
yeah, totally forgot about it, let's see how long it will take (:

**Comment by fabxc** [comment]
Can you squash this together into a few meaningful commits? I'd like to avoid stuff like "Poking CI" in the overall history.

**Comment by Bplotka** [comment]
Closing this PR in favor of clean https://github.com/improbable-eng/promlts/pull/15

**Pull request closed without merging**
