### PR TITLE
Removed unused gateway.

### PR DESCRIPTION
**Pull request by Bplotka**

### CODE REVIEW

**Comment by fabxc** [comment]
`golang.org/x/net/context` is legacy. With go1.9 there should be type aliases now which no longer requires importing both context packages.

Do you have `go1.8` or lower installed by any chance?

**Comment by Bplotka** [comment]
Yup, I did not update to go 1.9 yet, removing that change then (:

**Comment by Bplotka** [comment]
OK, I think we have some Travis bug or default travis logic when there is no Travis.yaml ): https://travis-ci.org/improbable-eng/promlts/builds/296370778?utm_source=github_status&utm_medium=notification

We need to merge https://github.com/improbable-eng/promlts/pull/14 first

**Comment by Bplotka** [comment]
Removing this PR in favor of clean https://github.com/improbable-eng/promlts/pull/15

**Pull request closed without merging**
